-- Copyright (c) Jérémie N'gadi
--
-- All rights reserved.
--
-- Even if 'All rights reserved' is very clear :
--
--   You shall not use any piece of this software in a commercial product / service
--   You shall not resell this software
--   You shall not provide any facility to install this particular software in a commercial product / service
--   If you redistribute this software, you must link to ORIGINAL repository at https://github.com/ESX-Org/es_extended
--   This copyright should appear in every part of the project code

-- Citizen.CreateThread(function()
-- 	local char = module.PlateLetters
-- 	char = char + module.PlateNumbers
-- 	if module.PlateUseSpace then char = char + 1 end

-- 	if char > 8 then
-- 		print(('[esx_vehicleshop] [^3WARNING^7] Plate character count reached, %s/8 characters!'):format(char))
-- 	end
-- end)
